"use client";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RightNavbar from '@/components/RightNavbar'
import { Toaster } from 'react-hot-toast'
import ModelProvider from '@/components/ModelProvider'
import { SocketProvider } from '@/contexts/socket-provider'
import { UserProvider } from '@/contexts/ContextProvider'
import { ThemeProvider } from '@/contexts/themeProvider'
import QueryProvider from '@/contexts/QueryProvider'
import BottomNav from '@/components/BottomNav'
import TopNav from '@/components/TopNav'
import SupabaseProvider from '@/contexts/supabaseProvider'
import SuggestedUserBar from '@/components/SuggestedUserBar'
import { usePathname } from 'next/navigation';
import ConversationsSideBar from '@/components/ConversationsSideBar';


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();

  const paths = [
    '/login',
    '/signup',
    '/forgot-password',
    '/verify-account',
    '/update-password',
    '/resend-verification-email',
    '/accessToken-expired',
  ];

  const shouldShow = paths.includes(pathname!)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: 'flex', justifyContent: 'end' }} className='w-full h-[100vh] flex justify-between items-center overflow-hidden dark:bg-black bg-white box-border '>
          <QueryProvider>
            <ThemeProvider>
              <SocketProvider>
                <SupabaseProvider>
                  <Toaster />
                  <UserProvider>
                    <ModelProvider>
                      <TopNav />
                      <RightNavbar />
                      <BottomNav />
                      <ConversationsSideBar />
                      <div className={`w-full h-full ${(!shouldShow || pathname?.startsWith( '/conversations' || '/conversations/') ) && 'md:w-[670px]'}  overflow-hidden overflow-y-auto custom-scrollbar  `}>
                        {children}
                      </div>
                      <SuggestedUserBar />
                    </ModelProvider>
                  </UserProvider>
                </SupabaseProvider>
              </SocketProvider>
            </ThemeProvider>
          </QueryProvider>
        </div>
      </body>
    </html>
  )
}
