

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RightNavbar from '@/components/RightNavbar'
import { Toaster } from 'react-hot-toast'
import ModelProvider from '@/components/ModelProvider'
import { SocketProvider } from '@/contexts/socket-provider'
import { UserProvider } from '@/contexts/ContextProvider'
import { ThemeProvider } from '@/contexts/themeProvider'





const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full h-[100vh] flex col-auto '>
          <SocketProvider>
            <Toaster />
            <UserProvider>
              <ThemeProvider>
                <ModelProvider>
                  <RightNavbar />
                  <div className='w-full overflow-hidden overflow-y-auto'>
                    {children}
                  </div>
                </ModelProvider>
              </ThemeProvider>
            </UserProvider>
          </SocketProvider>
        </div>
      </body>
    </html>
  )
}
